- name: Ensure that the software folder already exists
  file: path="{{ ansible_env.PWD }}/software" state=directory mode=0777

- name: Clone the streamformatics github repository
  git:
     repo: https://github.com/mbhall88/streamformatics.git 
     dest: "{{ ansible_env.PWD }}/software/streamformatics"
     clone: yes
     update: yes

- name: Clone the Jaspa github repository
  git:
      repo: https://github.com/mdcao/japsa.git
      dest: "{{ ansible_env.PWD}}/software/jaspa-src"
      clone: yes
      update: yes

- name: Ensure that javac is installed
  apt: 
    name: default-jdk
    state: present
  become: true
  become_user: root

- name: Run the make on the jaspa 
  command: "make install INSTALL_DIR={{ ansible_env.PWD }}/software/jaspa MXMEM=7000m SERVER=true JLP=false"
  args:
      chdir: "{{ ansible_env.PWD }}/software/jaspa-src"
