- name: Ensure that the software folder already exists
  file: path="{{ ansible_env.PWD }}/software" state=directory mode=0777

- include: streamformatics.yml

- name: Ensure that javac is installed
  apt:
    name: default-jdk
    state: present
  become: true
  become_user: root

- include: japsa.yml

- name: Ensure that nodejs is installed
  apt:
    name: nodejs
  become: true
  become_user: root

- name: Install packages based on package.json.
  npm:
    path: "{{ ansible_env.PWD }}/software/streamformatics"
    state: latest

- name: Install h5py and watchdog python packages
  pip: name={{ item }}
  with_items:
    - h5py
    - watchdog
