- name: Clone the minimap2 from the repository
  git:
      repo: https://github.com/lh3/minimap2
      dest: "{{ ansible_env.PWD}}/software/minimap2"
      clone: yes
      update: yes


- name: Run the make on minimap2
  command: "make"
  args:
      chdir: "{{ ansible_env.PWD }}/software/minimap2"

- name: "Add minimap2 to .bashrc"
  shell: echo export PATH={{ ansible_env.PWD }}/software/minimap2:$PATH >> {{ ansible_env.PWD }}/.bashrc
