- name: Ensure that the software folder already exists
  file: path="{{ ansible_env.PWD }}/software" state=directory mode=0777

- include: streamformatics.yml

# Check if java is installed.

- include: japsa.yml

# Ensure that nodejs is installed.

- name: Install packages based on package.json.
  npm:
    path: "{{ ansible_env.PWD }}/software/streamformatics"

- name: Install h5py and watchdog python packages
  pip: name={{ item }}
  with_items:
    - h5py
    - watchdog

- include: minimap2.yml
